import os

from dotenv import load_dotenv


load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "ml-latest-small")
MOVIES_CSV = os.path.join(DATA_DIR, "movies.csv")
RATINGS_CSV = os.path.join(DATA_DIR, "ratings.csv")
TAGS_CSV = os.path.join(DATA_DIR, "tags.csv")
EMBEDDING_PATH = os.path.join(BASE_DIR, "movies_embeddings.npy")
METADATA_PATH = os.path.join(BASE_DIR, "movies_metadata.parquet")
SPACY_MODEL_NAME = "en_core_web_lg"

# Genre Mapping Dictionary
GENRE_MAPPING = {
    "comedy": [
        "funny",
        "humorous",
        "hilarious",
        "sitcom",
        "laugh",
        "comedy",
        "joke",
        "gag",
        "parody",
        "satire",
        "slapstick",
        "comical",
        "witty",
    ],
    "horror": [
        "scary",
        "creepy",
        "terrifying",
        "ghost",
        "zombie",
        "spooky",
        "gore",
        "horror",
        "slasher",
        "nightmare",
        "monster",
        "supernatural",
        "paranormal",
        "haunted",
        "blood",
        "scream",
    ],
    "action": [
        "fight",
        "explosion",
        "combat",
        "chase",
        "battle",
        "gun",
        "stunt",
        "action",
        "adventure",
        "heroic",
        "martial arts",
        "shootout",
        "mission",
        "warrior",
        "fast-paced",
    ],
    "romance": [
        "love",
        "relationship",
        "dating",
        "couple",
        "romantic",
        "marriage",
        "soulmate",
        "passion",
        "affection",
        "heartwarming",
        "wedding",
        "kiss",
        "partner",
    ],
    "sci-fi": [
        "science fiction",
        "space",
        "alien",
        "future",
        "robot",
        "cyberpunk",
        "technology",
        "advanced",
        "spacecraft",
        "interstellar",
        "time travel",
        "artificial intelligence",
        "dystopian",
        "futuristic",
    ],
    "thriller": [
        "suspense",
        "mystery",
        "tense",
        "intrigue",
        "psychological",
        "twist",
        "conspiracy",
        "intense",
        "danger",
        "nail-biting",
        "edge of seat",
        "unpredictable",
    ],
    "drama": [
        "serious",
        "story",
        "character",
        "emotional",
        "conflict",
        "tragedy",
        "struggle",
        "realistic",
        "powerful",
        "moving",
        "profound",
        "life-changing",
        "thought-provoking",
    ],
    "fantasy": [
        "magic",
        "myth",
        "dragon",
        "wizard",
        "fairy tale",
        "supernatural",
        "enchanted",
        "mystical",
        "sorcery",
        "legendary",
        "mythological",
        "epic",
        "imaginary world",
    ],
    "animation": [
        "cartoon",
        "animated",
        "drawn",
        "cgi",
        "pixar",
        "disney",
        "anime",
        "claymation",
        "stop-motion",
        "3d animation",
        "hand-drawn",
    ],
    "documentary": [
        "real",
        "non-fiction",
        "history",
        "nature",
        "educational",
        "informative",
        "factual",
        "interview",
        "archive footage",
        "investigation",
        "biographical",
        "documentary",
    ],
    "adventure": [
        "journey",
        "quest",
        "expedition",
        "exploration",
        "discover",
        "travel",
        "danger",
        "exciting",
        "thrilling",
        "wilderness",
        "survival",
        "treasure",
        "uncharted",
    ],
    "children": [
        "kids",
        "family",
        "child-friendly",
        "youth",
        "coming-of-age",
        "innocent",
        "playful",
        "educational",
        "young",
        "school",
        "childhood",
        "juvenile",
    ],
    "crime": [
        "detective",
        "police",
        "criminal",
        "heist",
        "murder",
        "investigation",
        "robbery",
        "gangster",
        "mafia",
        "cop",
        "forensic",
        "prison",
        "vigilante",
        "organized crime",
    ],
    "war": [
        "battle",
        "military",
        "soldier",
        "combat",
        "army",
        "navy",
        "air force",
        "conflict",
        "battlefield",
        "war",
        "historical war",
        "trench",
        "warfare",
        "veteran",
    ],
    "musical": [
        "song",
        "dance",
        "singing",
        "choreography",
        "musical",
        "broadway",
        "performance",
        "stage",
        "concert",
        "music",
        "theatrical",
        "opera",
        "lyrical",
    ],
    "imax": [
        "large format",
        "immersive",
        "panoramic",
        "giant screen",
        "high resolution",
        "vivid",
        "spectacular",
        "visual spectacle",
    ],
    "western": [
        "cowboy",
        "frontier",
        "gunslinger",
        "wild west",
        "ranch",
        "sheriff",
        "outlaw",
        "desert",
        "saloon",
        "duel",
        "horseback",
        "rodeo",
    ],
    "film-noir": [
        "dark",
        "gritty",
        "detective",
        "femme fatale",
        "shadowy",
        "crime drama",
        "moody",
        "cynical",
        "hard-boiled",
        "psychological",
        "black and white",
        "mysterious",
    ],
    "mystery": [
        "clue",
        "detective",
        "puzzle",
        "enigma",
        "investigation",
        "whodunit",
        "suspense",
        "secrets",
        "riddle",
        "hidden",
        "reveal",
        "plot twist",
        "mysterious",
    ],
}

# Keyword to Genre mapping for faster lookups
KEYWORD_TO_GENRE = {}
for genre, keywords in GENRE_MAPPING.items():
    for keyword in keywords:
        KEYWORD_TO_GENRE[keyword] = genre

# Recommendation Weights
SIMILARITY_WEIGHT = 0.7
RATING_WEIGHT = 0.3

print("Configuration loaded.")
